services:
  # Nosso site Next.js
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_PB_URL=http://backend:8090
    depends_on:
      - backend

  # Nosso Banco PocketBase
  backend:
    image: alpine:latest
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data  # Pasta no seu Windows : Pasta no Linux do Docker
      - ./pocketbase:/usr/local/bin/pocketbase
    # Adicionamos o parâmetro --dir /pb_data para forçar o PocketBase a ler a pasta certa
    entrypoint: ["sh", "-c", "chmod +x /usr/local/bin/pocketbase && /usr/local/bin/pocketbase serve --http=0.0.0.0:8090 --dir=/pb_data"]